const Dogs = [
    { id:1,
      name: 'Coco',
      age: 'Adult',
      type: 'Husky',
      size: 'Large',
      gender: 'Female',
      picture: './assets/coco.png',
      color:'white',
      kids: 'Ok w/ Kids over age 16',
      cats: 'No cats',
      dog:'OK w/ introduction'
    },
    { id:2,
      name: 'Yoshi',
      age: 'Senior',
      gender:'Female',
      type: 'Terrier',
      size: 'Medium',
      picture: './assets/yoshi.png',
      color: null,
      kids: null,
      cats: null,
      dog: null
    },
    { id:3,
      name: 'Max',
      age: 'Adult',
      gender:'Male',
      type: 'German Shepherd',
      size: 'Large',
      picture: './assets/max.png',
      color: null,
      kids: null,
      cats: null,
      dog: null
    },
    {  id:4,
        name: 'Oreo',
        age: 'Adult',
        gender:'Female',
        type: 'Pit Bull Terrier',
        size: 'Large',
        picture: './assets/oreo.png',
        color: null,
        kids: null,
        cats: null,
        dog: null

    },
    {   id:5,
        name: 'Bella',
        age: 'Young',
        gender:'Female',
        type: 'Pit Bull Terrier',
        size: 'Large',
        picture: './assets/bella.png',
        color: null,
        kids: null,
        cats: null,
        dog: null
    },
    {   id:6,
        name: 'Ross',
        age: 'Adult',
        gender:'Male',
        type: 'German Shepherd',
        size: 'Large',
        picture: './assets/ross.png',
        color: null,
      kids: null,
      cats: null,
      dog: null
      
    }
  ];
  
  export default Dogs;